const fs = require('fs');
const path = require('path');
const mainIndex = path.join(__dirname, 'index.html');
const templateIndex = path.join(__dirname, 'viseas-html', 'index.html');
let mainContent = fs.readFileSync(mainIndex, 'utf8');
let tplContent = fs.readFileSync(templateIndex, 'utf8');
const targetImgDir = path.join(__dirname, 'assets', 'viseas');
if (!fs.existsSync(targetImgDir)) fs.mkdirSync(targetImgDir);
const sourceImgDir = path.join(__dirname, 'viseas-html', 'images');
const images = fs.readdirSync(sourceImgDir);
images.forEach(img => { fs.copyFileSync(path.join(sourceImgDir, img), path.join(targetImgDir, img)); });
const extractSection = (cls) => {
    let start = tplContent.indexOf('<section class="' + cls + '">');
    if(start === -1) start = tplContent.indexOf('<section class="' + cls + ' ">');
    if(start === -1) return '';
    let end = tplContent.indexOf('</section>', start);
    let str = tplContent.substring(start, end + 10);
    return str.split('images/').join('assets/viseas/');
};
let serviceSection = extractSection('service_section layout_padding');
let aboutSection = extractSection('about_section layout_padding');
let countrySection = extractSection('country_section layout_padding');
serviceSection = serviceSection.split('<a href="">').join('<a href="travel-fees.html?type=visitor" class="btn btn-success mt-3" style="background-color: #8BC34A; border:none; padding: 10px 20px; color: white;">');
const css = '<style>.service_section { background-color: #f8f9fa; text-align: center; padding: 60px 0; } .service_section .box { margin-bottom: 30px; padding: 35px 25px; background: #fff; box-shadow: 0 0 15px rgba(0,0,0,0.1); border-radius: 5px; transition: all .3s; } .service_section .box.active, .service_section .box:hover { background-color: #13110f; color: #fff; } .service_section h6 { font-size: 18px; font-weight: bold; margin-top: 15px; color: inherit; } .service_section p { margin-top: 10px; font-size: 14px; color: inherit; } .service_section .img-box { height: 65px; display: flex; justify-content: center; align-items: center; } .about_section { background-color: #13110f; color: #fff; padding: 75px 0; display:flex; align-items:center; } .about_section p { margin-top: 15px; margin-bottom: 25px; font-size: 15px; color: #ccc; } .about_section .btn-box a { display: inline-block; padding: 10px 45px; background-color: #8BC34A; color: #fff; border-radius: 0; text-transform: uppercase; font-weight: bold; } .about_section .img-box img { max-width: 100%; border-radius: 8px; } .country_section { padding: 60px 0; text-align: center; } .country_section .box { position: relative; display: block; margin-bottom: 30px; border-radius: 10px; overflow: hidden; } .country_section .box img { width: 100%; height: 250px; object-fit: cover; transition: transform .3s; } .country_section .box:hover img { transform: scale(1.1); } .country_section .detail-box { position: absolute; bottom: 0; left: 0; right: 0; background: rgba(0,0,0,0.6); padding: 15px; color: #fff; } .country_section h3 { margin: 0; font-size: 20px; font-weight: bold; } .heading_container { margin-bottom: 35px; } .heading_center { text-align: center; } .heading_container h2 { font-weight: bold; font-size: 32px; color: #13110f; text-transform: uppercase; } .about_section .heading_container h2 { color: #fff; } .viseas-row { display: flex; flex-wrap: wrap; margin: -15px; justify-content: center; } .viseas-col-6 { width: 50%; padding: 15px; } .viseas-col-4 { width: 33.333%; padding: 15px; }</style>';
serviceSection = serviceSection.split('class="row"').join('class="viseas-row"').split('class="col-md-6"').join('class="viseas-col-6"');
aboutSection = aboutSection.split('class="row"').join('class="viseas-row"').split('class="col-md-6"').join('class="viseas-col-6"').split('class="col-lg-6 px-0"').join('class="viseas-col-6"');
countrySection = countrySection.split('class="row"').join('class="viseas-row"').split('class="col-md-4"').join('class="viseas-col-4"');
let combined = css + '\n' + serviceSection + '\n' + aboutSection + '\n' + countrySection;
mainContent = mainContent.replace(/<section class="py-16 bg-white" id="visa-services">[\s\S]*?<\/section>/i, '');
mainContent = mainContent.replace('<section class="py-16 bg-slate-50" id="pathways">', combined + '\n    <section class="py-16 bg-slate-50" id="pathways">');
fs.writeFileSync(mainIndex, mainContent, 'utf8');
console.log('done!');
